Capstone project
Jolak5/life-with-Joseph pull request #1
Opened 2023-01-06 06:48 UTC by Jolak5

In this PR, I:

1. created the feature speaker section dynamically.
2. build a responsive nav menu. 
3. Built the about us and home sections. 

Here's a link to my life video - https://www.loom.com/share/26fcfe34b3324a68a689ea5d86108d48

2023-01-06 15:01 UTC, tresorsawasawa requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @Jolak5 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-06 15:01 UTC, tresorsawasawa commented on README.md
> +
- [ ] I think it would be better if you change this title to the one of your project as this project is not named `Hello_Microverse` but something else. This make your README looks more professional

2023-01-06 15:01 UTC, tresorsawasawa commented on index.html
>            <li class="nav-item"><a href="home.html">Home</a></li>
- [ ] Kindly make sure you fix the **home** option link to the working one as the current one is broken. If you you check from your files, no one is named `home.html`. I think you should update it to `<a href="./index.html">Home</a>` instead.

2023-01-06 15:01 UTC, tresorsawasawa commented on index.html
>            <li class="nav-item"><a href="about.html">About Us</a></li>
- [ ] I noticed that you have duplicated 2 times your navigation list. I think it would be better if you remove one block for clean code and best practices.

2023-01-06 15:01 UTC, tresorsawasawa commented on index.html
>            <li class="nav-item"><a href="about.html">About Us</a></li>
- [ ] Kindly make sure your **Header** is divided into two: a top dark bar and a bottom white bar. The top short bar section with social media links, logout, and language links aligned to the right. I can see that from your design you miss the dark top bar. Make sure to add it will all elements and well designed.

- [ ] Kindly make sure your bottom navbar design stick as much as the possible to the one from the template. 
e.g.: spacing between and around elements, `background color`, `fonts`, `text color`,...
From the images below you can see the difference between them. 

## Template Design
![Screenshot from 2023-01-06 15-16-02](https://user-images.githubusercontent.com/83042742/211020767-4859e48c-0fb3-40a6-a5e5-741f2380fae6.png)

## Your design
![Screenshot from 2023-01-06 15-18-39](https://user-images.githubusercontent.com/83042742/211020274-2def1a1b-b097-4d3d-ac9d-085d6101c410.png)

2023-01-06 15:01 UTC, tresorsawasawa commented on index.html
>          </h1>
- [ ] Kindly make sure your hero text design math the one from the template as required for the project. I thing you are still missing the background effect on the text, text transformation(uppercase), size, line heighr, weight,... to match the expected design.

### Template design
![Screenshot from 2023-01-06 15-27-36](https://user-images.githubusercontent.com/83042742/211021916-91d6e9b2-a144-41d7-a68c-9d5a5316efd8.png)

### Your Design
![Screenshot from 2023-01-06 15-29-27](https://user-images.githubusercontent.com/83042742/211022002-9e0c1b54-58ed-426b-9916-9ff57b872ed1.png)

2023-01-06 15:01 UTC, tresorsawasawa commented on index.html
>          </div>
- [ ] Kindly make sure your **Hero** section design sticks as much as possible as much as possible to the one of the Behance template. Right now, I noticed that there is something to improve again such as: adding the `background image`,  use correct `fonts(size, weight, family...)` on text, `padding`, `margin`, `text-colors`,... Make sure to take a look on the template a improve your design again in order to match the expected result.

| Template design | Your Design |
| -------------------- | --------------------- |
| ![Screenshot from 2023-01-06 15-30-28](https://user-images.githubusercontent.com/83042742/211023379-cf9e0271-ef52-49bd-9bb2-c6eaada478f2.png) | ![Screenshot from 2023-01-06 15-30-48](https://user-images.githubusercontent.com/83042742/211023406-5e9c7593-a22f-4457-9618-ee5de2994be8.png) |

2023-01-06 15:01 UTC, tresorsawasawa commented on index.html
>          <h4>JOIN ME LIVE (WED) ~ 6PM</h4>
- [ ] **Main Program Section:** Kindly make sure your main section design sticks as much as possible to the one from the template design. e.g.:  background color, text color, different icons in each card, interraction on a card when it is hovered, styling other element,...
You can take a look to the images below, see the big difference and then improve your design:

| Template design | Your Design |
| -------------------- | --------------------- |
| ![Screenshot from 2022-11-23 23-41-50](https://user-images.githubusercontent.com/83042742/211024990-a1575ac8-b203-48a7-be73-79178c89f9da.png) | ![Screenshot from 2023-01-06 15-48-09](https://user-images.githubusercontent.com/83042742/211025106-c8d559f9-9adc-40b5-94ed-a19db1c78ebc.png) |

- [ ] Kindly make sure your **Join me on Sportify** button is correctly styled for both on **Mobile** and desk top versio. You can see the image from desk in the image above for mobile below: 

| Template design | Your Design |
| ------------------ | -------------------- |
| ![Screenshot from 2023-01-06 16-56-04](https://user-images.githubusercontent.com/83042742/211037445-fe3e6f27-fc57-48b0-89cc-45efd51d9bee.png) | ![Screenshot from 2023-01-06 16-55-33](https://user-images.githubusercontent.com/83042742/211037496-4c7e4caa-b1e5-4460-b4b7-1412246426e8.png) |

2023-01-06 15:01 UTC, tresorsawasawa commented on home.js
> +
- [ ] Kindly make sure you fix your linters errors instead of disabling them. This for best practices, clean code anf for the project requirements.

2023-01-06 15:01 UTC, tresorsawasawa commented on home.js
>    },
- [ ] Kindly make sure your `Featured Speakers` section design sticks as much as possible to the one of the template. E.g.: fonts(size, weight,...) on text, use a grid background image on each speaker picture, alignment of different elements, **use different speakers with different pictures**,... Make sure sure you check all details and improve your design to be close the one of the template. I know you can do it :muscle: :muscle: 

### Template design 
![Screenshot from 2023-01-06 16-03-29](https://user-images.githubusercontent.com/83042742/211028569-a8142277-7600-45cc-9bf7-ec3cbb75fc03.png) 
### Your Design 
 ![Screenshot from 2023-01-06 15-54-41](https://user-images.githubusercontent.com/83042742/211028615-9e816178-ead2-47df-b067-ed6bd31b15a8.png) |

2023-01-06 15:01 UTC, tresorsawasawa commented on index.html
>          All rights reserved
- [ ] Kindly make sure you fix the broken image of your logo at the footer. I think this is because of a typing error. You wrote `Logo.png` instead of `logo.png`.

- [ ] Kindly make sure your footer design stick to the one from the template for both pages(**Home** and **About** pages). 

| Template Home footer | Template About footer |
| ---------------------------- | ------------------------------ |
| ![Screenshot from 2023-01-06 16-12-08](https://user-images.githubusercontent.com/83042742/211030194-f5965ecd-bd71-4cf2-b276-5108e1307687.png) | ![Screenshot from 2023-01-06 16-19-53](https://user-images.githubusercontent.com/83042742/211030312-c062d328-0e92-4300-874e-3034fe3405ca.png) |

| Your Home footer | Your About footer |
| ---------------------------- | ------------------------------ |
| ![Screenshot from 2023-01-06 16-17-41](https://user-images.githubusercontent.com/83042742/211030599-bf1cf02e-e322-45a1-af01-7a3766e46619.png) | ![Screenshot from 2023-01-06 16-18-15](https://user-images.githubusercontent.com/83042742/211030836-d1110d4a-50b4-4c31-8335-5d67a828894e.png) |

2023-01-06 15:01 UTC, tresorsawasawa commented on about.html
>              eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
- [ ] Kindly make sure the **about Hero section** design stick as much as possible to the one from the template as required for the project. You should use the correct `fonts(size, weigt,...)` `Uppercase the hero` text , line height, padding, margin, add all possible text elements, background image,... 

### Template design
![Screenshot from 2023-01-06 16-29-43](https://user-images.githubusercontent.com/83042742/211033036-c605f259-95a8-4ba4-9908-faef243e9f05.png)

### Your Design
![Screenshot from 2023-01-06 16-24-07](https://user-images.githubusercontent.com/83042742/211033124-1af16274-1e2c-493d-b771-77532760abcf.png)

2023-01-06 15:01 UTC, tresorsawasawa commented on about.html
>        <h3>See the recent podcast</h3>
- [ ] Kindly make sure you use the correct font size on all the sections text to match the expected design.

2023-01-06 15:01 UTC, tresorsawasawa commented on index.html
>            <li class="nav-item"><a href="about.html">About Us</a></li>
- [ ] Kindly make sure you improve the design of the mobile menu of the both pages to web page looks smart and professional. Below is how your mobile menu looks now. 
- [ ] I think it would be better if you correctly design the close menu button and adjust all the overlapping stlyling elements.

| mobile memu | mobile menu |
| ---------------- | ------------------- |
| ![Screenshot from 2023-01-06 16-43-41](https://user-images.githubusercontent.com/83042742/211035644-9dcf3d5d-5ebf-435b-9230-8cb584424569.png) | ![Screenshot from 2023-01-06 16-45-02](https://user-images.githubusercontent.com/83042742/211035788-56220512-422a-4f89-b319-949fff900c79.png) |

2023-01-06 15:01 UTC, tresorsawasawa commented on about.html
>          <ul class="nav-menu">
- [ ] Kindly make sure you apply all design improvement for the **MOBILE** && **DESKTOP** versions for all the pages, you should use the exact same `colors`, for text, **backgrounds**, **borders**, etc, from the **[original design.](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015)**

2023-01-06 22:47 UTC, jerryowusu requested changes
Hi @Jolak5 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![so close](https://user-images.githubusercontent.com/65233860/211112598-40b15b43-e474-4c85-97a7-01339a2b565b.gif)


 ## Highlights
All linters are passing :heavy_check_mark: 
Great effort so far :heavy_check_mark: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-06 22:47 UTC, jerryowusu commented on index.html
>          <h4>JOIN ME LIVE (WED) ~ 6PM</h4>
Kindly ensure that your main program section looks like the design at all screen sizes of the desktop version. 

- [ ] Kindly check the margins and paddings and ensure they conform to the design at all screen widths especially at around width of 865px. 

- [ ] I can also see some differences in the `Join me on spotify` button, it does not have the red background on the desktop version but rather underlined. Please check and rectify this issue. :pray: 

| Original design | Your Design |
| -------------------- | --------------------- |
![Screenshot from 2023-01-06 22-17-31](https://user-images.githubusercontent.com/65233860/211110508-8574106b-8c6d-4a80-9c1a-23a79ed18c86.png)  |  ![Screenshot from 2023-01-06 22-28-15](https://user-images.githubusercontent.com/65233860/211110522-7119d2b1-7ee9-40f3-b83c-4775698c1e61.png)

2023-01-06 22:47 UTC, jerryowusu commented on about.html
> +      <h2> Podcast - Life with Joseph 2015</h2>
As requested by the previous reviewer, kindly make sure you use the correct font size on all the sections text to match the expected design. Most of the font-sizes of the about page looks bigger than the original design. Kindly adjust them to match the design. :pray:

2023-01-06 22:47 UTC, jerryowusu commented on index.html
>      <section class="partners-container">
[OPTIONAL] One of the images of the partner section is broken as shown below, kindly check and fix it

![Screenshot from 2023-01-06 22-43-42](https://user-images.githubusercontent.com/65233860/211112430-d4fbfebe-708b-49a1-85f6-0ee8bfa611b9.png)

2023-01-07 08:52 UTC, PinkMoon25 approved these changes
Hi @Jolak5 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
linter checks :heavy_check_mark: 
Readme :heavy_check_mark: 
github flow :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-07 10:58 UTC, merged